In [1]:
import tensorflow as tf

In [5]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1], name='weight1'))
w2 = tf.Variable(tf.random_normal([1], name='weight2'))
w3 = tf.Variable(tf.random_normal([1], name='weight3'))
b = tf.Variable(tf.random_normal([1], name='bias'))

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

#cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 ==0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  152.0 
Prediction:
 [ 0.  0.  0.  0.  0.]
10 Cost:  75.0 
Prediction:
 [  1.40129846e-45   1.85000000e+02   1.80000000e+02   1.96000000e+02
   1.42000000e+02]
20 Cost:  75.0 
Prediction:
 [  75.   93.   90.  100.   70.]
30 Cost:  75.0 
Prediction:
 [  75.   93.   90.  100.   70.]
40 Cost:  0.0 
Prediction:
 [   0.  185.  180.  196.  142.]
50 Cost:  0.0 
Prediction:
 [   0.   93.   90.  100.   70.]
60 Cost:  0.0 
Prediction:
 [  7.00649232e-45   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00]
70 Cost:  7.00649e-45 
Prediction:
 [  7.00649232e-45   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00]
80 Cost:  1.4013e-45 
Prediction:
 [  7.00649232e-45   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00]
90 Cost:  7.00649e-45 
Prediction:
 [  7.00649232e-45   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00]
100 Cost:  7.00649e-45 
Prediction:
 [  7.00649232e-45   0.00000000e+00   0.00000000e+00   0.00000000e+

910 Cost:  1.27114 
Prediction:
 [ 152.57606506  183.83197021  180.90135193  197.00959778  140.31838989]
920 Cost:  1.26594 
Prediction:
 [ 152.57235718  183.83451843  180.90023804  197.00860596  140.32189941]
930 Cost:  1.26074 
Prediction:
 [ 152.56866455  183.83708191  180.89912415  197.00761414  140.32540894]
940 Cost:  1.2556 
Prediction:
 [ 152.56498718  183.83963013  180.89804077  197.00665283  140.32891846]
950 Cost:  1.25049 
Prediction:
 [ 152.56132507  183.84214783  180.89692688  197.00566101  140.33239746]
960 Cost:  1.24539 
Prediction:
 [ 152.55767822  183.84469604  180.89584351  197.00468445  140.33587646]
970 Cost:  1.24032 
Prediction:
 [ 152.55401611  183.84721375  180.89474487  197.00367737  140.33934021]
980 Cost:  1.23529 
Prediction:
 [ 152.55036926  183.84971619  180.89364624  197.00271606  140.3427887 ]
990 Cost:  1.23027 
Prediction:
 [ 152.54673767  183.85221863  180.89256287  197.0017395   140.34625244]
1000 Cost:  1.22528 
Prediction:
 [ 152.54312134  183.85

1840 Cost:  0.888606 
Prediction:
 [ 152.27229309  184.04196167  180.81048584  196.92648315  140.6086731 ]
1850 Cost:  0.885438 
Prediction:
 [ 152.26942444  184.04393005  180.80963135  196.92567444  140.61141968]
1860 Cost:  0.882284 
Prediction:
 [ 152.2665863   184.0459137   180.80879211  196.92489624  140.61418152]
1870 Cost:  0.879142 
Prediction:
 [ 152.26374817  184.04786682  180.80793762  196.92408752  140.6169281 ]
1880 Cost:  0.876016 
Prediction:
 [ 152.26091003  184.04985046  180.80709839  196.92329407  140.61965942]
1890 Cost:  0.872919 
Prediction:
 [ 152.25808716  184.05180359  180.80625916  196.92250061  140.62237549]
1900 Cost:  0.869837 
Prediction:
 [ 152.25526428  184.05374146  180.80541992  196.92170715  140.62509155]
1910 Cost:  0.866758 
Prediction:
 [ 152.25245667  184.05569458  180.80458069  196.9209137   140.62780762]
1920 Cost:  0.863708 
Prediction:
 [ 152.24966431  184.05764771  180.80375671  196.9201355   140.63050842]
1930 Cost:  0.86066 
Prediction:
 [ 1

In [8]:
x_data = [
    [73., 80., 75.], [93., 88., 93.], 
    [89., 91.,98.],  [96., 90., 100.], 
    [73., 66., 70.]]

y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1], name='weight'))
b = tf.Variable(tf.random_normal([1], name='bias'))

hypothesis = tf.matmul(X, W) + b

#cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 ==0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  125.999 
Prediction:
 [[ 166.11154175]
 [ 190.50491333]
 [ 199.74377441]
 [ 199.20606995]
 [ 142.67750549]]
10 Cost:  48.729 
Prediction:
 [[ 158.32356262]
 [ 181.18025208]
 [ 190.25453186]
 [ 189.46955872]
 [ 135.57623291]]
20 Cost:  48.5003 
Prediction:
 [[ 158.27262878]
 [ 181.16252136]
 [ 190.21078491]
 [ 189.45210266]
 [ 135.57392883]]
30 Cost:  48.2737 
Prediction:
 [[ 158.24525452]
 [ 181.17303467]
 [ 190.19573975]
 [ 189.46405029]
 [ 135.59313965]]
40 Cost:  48.0484 
Prediction:
 [[ 158.21806335]
 [ 181.18357849]
 [ 190.18083191]
 [ 189.47608948]
 [ 135.61235046]]
50 Cost:  47.8243 
Prediction:
 [[ 158.19093323]
 [ 181.1940918 ]
 [ 190.16592407]
 [ 189.48806763]
 [ 135.6315155 ]]
60 Cost:  47.6015 
Prediction:
 [[ 158.16390991]
 [ 181.2046051 ]
 [ 190.15107727]
 [ 189.50001526]
 [ 135.65063477]]
70 Cost:  47.3799 
Prediction:
 [[ 158.13697815]
 [ 181.21508789]
 [ 190.13626099]
 [ 189.51191711]
 [ 135.66970825]]
80 Cost:  47.1596 
Prediction:
 [[ 158.11012268]
 [ 181.22

900 Cost:  32.7129 
Prediction:
 [[ 156.18093872]
 [ 181.99671936]
 [ 189.01585388]
 [ 190.37016296]
 [ 137.092453  ]]
910 Cost:  32.5744 
Prediction:
 [[ 156.16046143]
 [ 182.00515747]
 [ 189.00360107]
 [ 190.37905884]
 [ 137.1078186 ]]
920 Cost:  32.4365 
Prediction:
 [[ 156.14006042]
 [ 182.01358032]
 [ 188.99137878]
 [ 190.38795471]
 [ 137.12315369]]
930 Cost:  32.2993 
Prediction:
 [[ 156.11972046]
 [ 182.02197266]
 [ 188.97915649]
 [ 190.39680481]
 [ 137.13842773]]
940 Cost:  32.1629 
Prediction:
 [[ 156.09944153]
 [ 182.03036499]
 [ 188.96696472]
 [ 190.40562439]
 [ 137.15368652]]
950 Cost:  32.0272 
Prediction:
 [[ 156.07922363]
 [ 182.03872681]
 [ 188.95480347]
 [ 190.41442871]
 [ 137.16888428]]
960 Cost:  31.8923 
Prediction:
 [[ 156.05908203]
 [ 182.04704285]
 [ 188.94267273]
 [ 190.42318726]
 [ 137.18405151]]
970 Cost:  31.7582 
Prediction:
 [[ 156.03900146]
 [ 182.05537415]
 [ 188.93058777]
 [ 190.43191528]
 [ 137.19918823]]
980 Cost:  31.6248 
Prediction:
 [[ 156.01899719

1600 Cost:  24.6297 
Prediction:
 [[ 154.89881897]
 [ 182.53907776]
 [ 188.21939087]
 [ 190.92471313]
 [ 138.07922363]]
1610 Cost:  24.5351 
Prediction:
 [[ 154.88258362]
 [ 182.54615784]
 [ 188.20889282]
 [ 190.93171692]
 [ 138.09210205]]
1620 Cost:  24.4411 
Prediction:
 [[ 154.86637878]
 [ 182.55322266]
 [ 188.19839478]
 [ 190.93864441]
 [ 138.10493469]]
1630 Cost:  24.3475 
Prediction:
 [[ 154.85023499]
 [ 182.56027222]
 [ 188.18792725]
 [ 190.9455719 ]
 [ 138.11775208]]
1640 Cost:  24.2544 
Prediction:
 [[ 154.83415222]
 [ 182.56729126]
 [ 188.17747498]
 [ 190.95248413]
 [ 138.13052368]]
1650 Cost:  24.1618 
Prediction:
 [[ 154.81811523]
 [ 182.57429504]
 [ 188.16703796]
 [ 190.95935059]
 [ 138.14328003]]
1660 Cost:  24.0697 
Prediction:
 [[ 154.80215454]
 [ 182.58129883]
 [ 188.15666199]
 [ 190.96621704]
 [ 138.15600586]]
1670 Cost:  23.9781 
Prediction:
 [[ 154.78620911]
 [ 182.58825684]
 [ 188.14627075]
 [ 190.97303772]
 [ 138.16867065]]
1680 Cost:  23.887 
Prediction:
 [[ 154.